services:
  microstrategy-metadata-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: microstrategy-metadata-api
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../logs:/app/logs
      - ../results:/app/results
    restart: unless-stopped